title: jet_so
logo: /assets/img/logo.png
description: I make videos about whatever I think is cool, Like tech and video editing.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
other:
  yt: https://www.youtube.com/channel/UCfFZ1QAWU3vIfmk1OA-oz6A
  hooktube: https://hooktube.com/channel/UCfFZ1QAWU3vIfmk1OA-oz6A
  video rss: https://pygy.co/jetso
