title: jet_so
logo: /assets/img/logo.png
description: I make videos about whatever I think is cool, Like tech and video editing.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
other:
  yt: https://jet-so.github.io/youtube/
  website_rss: https://jet-so.github.io/blogRSS/
  video_rss: https://jet-so.github.io/rss/
